# Generated by Django 3.2.12 on 2022-08-05 16:15

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Image Name')),
                ('image', models.ImageField(upload_to=images.models.imageset_upload_images_path)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(help_text='eg. Delhi-trip, Tajmahal, flowers', max_length=100)),
                ('description', models.TextField()),
                ('dirpath', models.CharField(blank=True, max_length=150, null=True)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
