# Generated by Django 3.2.12 on 2022-08-04 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagefile',
            name='image_set',
            field=models.ForeignKey(help_text='Image Set of the uploading images', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.imageset'),
        ),
    ]
