# Generated by Django 3.2.12 on 2022-08-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='is_inferrenced',
            field=models.BooleanField(default=False),
        ),
    ]
