# Generated by Django 3.2.12 on 2022-08-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
