# Generated by Django 3.2.12 on 2022-08-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Image Name'),
        ),
    ]
