# Generated by Django 3.2.12 on 2022-08-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imagefile_is_inferrenced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='is_inferrenced',
            new_name='is_inferenced',
        ),
    ]
