# Generated by Django 3.2.12 on 2022-08-04 14:43

import django.core.validators
from django.db import migrations, models
import modelmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0002_mlmodel_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='class_file',
            field=models.FileField(help_text='Ml Model classes file. Allowed extensions are: .txt, .names, .yaml', upload_to=modelmanager.models.model_classfile_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'TXT', 'names', 'names', 'yaml', 'YAML'])], verbose_name='Ml Model Classes file'),
        ),
    ]
