# Generated by Django 3.2.12 on 2022-08-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0004_mlmodel_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='class_filname',
            field=models.CharField(help_text='Name for the class file', max_length=100, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(help_text='Name for the machine learning model', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
