# Generated by Django 3.2.12 on 2022-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0005_auto_20220804_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='class_filname',
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='class_filename',
            field=models.CharField(help_text='Name for the class file', max_length=100, null=True, unique=True, verbose_name='Class FileName'),
        ),
    ]
