# Generated by Django 3.2.12 on 2022-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0006_auto_20220804_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='class_filename',
            field=models.CharField(help_text='Name for the class file', max_length=100, null=True, verbose_name='Class FileName'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(help_text='Name for the machine learning model', max_length=100, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='mlmodel',
            constraint=models.UniqueConstraint(fields=('name', 'uploader'), name='unique_model_by_user'),
        ),
    ]
