# Generated by Django 3.2.12 on 2022-08-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelmanager', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferencedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('inf_image_path', models.CharField(blank=True, max_length=250, null=True)),
                ('detection_info', models.JSONField(blank=True, null=True)),
                ('yolo_model', models.CharField(blank=True, choices=[('yolov5s.pt', 'yolov5s.pt'), ('yolov5m.pt', 'yolov5m.pt'), ('yolov5l.pt', 'yolov5l.pt'), ('yolov5x.pt', 'yolov5x.pt')], default=('yolov5s.pt', 'yolov5s.pt'), help_text='Selected yolo model will download.                                  Requires an active internet connection.', max_length=250, null=True, verbose_name='YOLOV5 Models')),
                ('model_conf', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Model confidence')),
                ('custom_model', models.ForeignKey(blank=True, help_text='Machine Learning model for detection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detectedimages', to='modelmanager.mlmodel', verbose_name='Custom ML Models')),
                ('orig_image', models.ForeignKey(blank=True, help_text='Main Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detectedimages', to='images.imagefile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
