# Generated by Django 3.2.12 on 2022-08-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelmanager', '0001_initial'),
        ('detectobj', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferrencedimage',
            name='custom_model',
            field=models.ForeignKey(blank=True, help_text='Machine Learning model for detection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detectedimages', to='modelmanager.mlmodel', verbose_name='Custom ML Models'),
        ),
        migrations.AddField(
            model_name='inferrencedimage',
            name='orig_image',
            field=models.ForeignKey(blank=True, help_text='Main Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detectedimages', to='images.imagefile'),
        ),
    ]
