# Generated by Django 3.2.12 on 2022-08-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectobj', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferrencedimage',
            name='yolo_model',
            field=models.CharField(blank=True, choices=[('yolov5s.pt', 'yolov5s.pt'), ('yolov5m.pt', 'yolov5m.pt'), ('yolov5l.pt', 'yolov5l.pt'), ('yolov5x.pt', 'yolov5x.pt')], default=('yolov5s.pt', 'yolov5s.pt'), help_text='Selected yolo model will download.                                  Requires an active internet connection.', max_length=250, null=True, verbose_name='YOLOV5 Models'),
        ),
    ]
