# Generated by Django 3.2.12 on 2022-08-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detectobj', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedetection',
            options={},
        ),
    ]
