# Generated by Django 3.2.12 on 2022-08-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0002_initial'),
        ('detectobj', '0003_alter_imagedetection_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedetection',
            name='detectionmodel',
        ),
        migrations.AddField(
            model_name='imagedetection',
            name='custommodel',
            field=models.ForeignKey(help_text='Model used for detection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detectedimages', to='modelmanager.mlmodel', verbose_name='Custom ML Models'),
        ),
        migrations.AddField(
            model_name='imagedetection',
            name='yolomodel',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='YOLOV5 Models'),
        ),
    ]
