# Generated by Django 3.2.12 on 2022-08-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0002_initial'),
        ('images', '0004_rename_is_inferrenced_imagefile_is_inferenced'),
        ('detectobj', '0003_alter_inferrencedimage_yolo_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InferrencedImage',
            new_name='InferencedImage',
        ),
    ]
