# Generated by Django 3.2.12 on 2022-08-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0002_initial'),
        ('images', '0003_imagefile_name'),
        ('detectobj', '0004_auto_20220805_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferrencedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('inf_image', models.ImageField(blank=True, null=True, upload_to='inferrenceimages')),
                ('detectioninfo', models.JSONField(blank=True, null=True)),
                ('yolomodel', models.CharField(blank=True, choices=[('yolov5s.pt', 'yolov5s.pt'), ('yolov5m.pt', 'yolov5m.pt'), ('yolov5l.pt', 'yolov5l.pt'), ('yolov5x.pt', 'yolov5x.pt')], max_length=250, null=True, verbose_name='YOLOV5 Models')),
                ('model_conf', models.PositiveIntegerField(blank=True, null=True, verbose_name='Model confidence')),
                ('custom_model', models.ForeignKey(help_text='Machine Learning model for detection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detectedimages', to='modelmanager.mlmodel', verbose_name='Custom ML Models')),
                ('orig_image', models.ForeignKey(blank=True, help_text='Main Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detectedimages', to='images.imagefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ImageDetection',
        ),
    ]
