# Generated by Django 3.2.12 on 2022-08-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectobj', '0005_auto_20220805_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inferrencedimage',
            old_name='detectioninfo',
            new_name='detection_info',
        ),
        migrations.RemoveField(
            model_name='inferrencedimage',
            name='yolomodel',
        ),
        migrations.AddField(
            model_name='inferrencedimage',
            name='yolo_model',
            field=models.CharField(blank=True, choices=[('yolov5s.pt', 'yolov5s.pt'), ('yolov5m.pt', 'yolov5m.pt'), ('yolov5l.pt', 'yolov5l.pt'), ('yolov5x.pt', 'yolov5x.pt')], help_text='Selected yolo model will download.                                  Requires an active internet connection.', max_length=250, null=True, verbose_name='YOLOV5 Models'),
        ),
    ]
