# Generated by Django 3.2.12 on 2022-08-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectobj', '0006_auto_20220805_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferrencedimage',
            name='inf_image',
        ),
        migrations.AddField(
            model_name='inferrencedimage',
            name='inf_image_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
