# Generated by Django 3.2.12 on 2022-08-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectobj', '0007_auto_20220805_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferrencedimage',
            name='model_conf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Model confidence'),
        ),
    ]
