# Generated by Django 3.2.12 on 2022-08-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0002_initial'),
        ('detectobj', '0008_alter_inferrencedimage_model_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferrencedimage',
            name='custom_model',
            field=models.ForeignKey(blank=True, help_text='Machine Learning model for detection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detectedimages', to='modelmanager.mlmodel', verbose_name='Custom ML Models'),
        ),
    ]
